---
locales_language_packs_present:
  - language-pack-en
  - language-pack-en-base
  - language-pack-zh-hans
  - language-pack-zh-hans-base

apt__source_types: [ 'deb', 'deb-src' ]
apt__distribution_components_free:
  'Debian':   [ 'main' ]
  'Raspbian': [ 'main', 'rpi' ]
  'Ubuntu':   [ 'main', 'restricted', 'universe', 'multiverse' ]

apt__distribution_suffix_map:
  'Debian_stable':   [ '', '-updates', '-backports' ]
  'Debian_testing':  [ '', '-updates' ]
  'Debian_unstable': [ '' ]
  'Raspbian':        [ '' ]
  'default':         [ '', '-updates', '-backports', '-security' ]

apt__repositories: []

apt__sources:
  - uri:          'https://mirrors.tuna.tsinghua.edu.cn/ubuntu/'
    comment:      '{{ "Tuna Mirror " + apt__distribution + " repositories" }}'
    distribution: 'Ubuntu'
apt__default_sources: []
apt__original_sources: []
apt__security_sources: []


git_install_from_source: true
git_version: '2.14.1'
git_install_from_source_force_update: true


git_config:
  user:
    name: "{{ git_user_name }}"
    email: "{{ git_user_email }}"
  core:
    editor: vim
    excludesfile: '~/.gitexcludesfile'
  push:
    default: simple


# A timezone (e.g. UTC, Europe/Amsterdam)
timezone_zone: 'Asia/Shanghai'


java_packages:
  - openjdk-8-jdk


nvm_version: "v0.33.2"
nvm_user: "{{ ansible_user }}"
nvm_node_version: "8.4.0"
nvm_npm_pkgs:
 - pkg: "node-gyp"
   version: "3.6.x"
 - pkg: "@adonisjs/cli"
   version: "*"
 - pkg: "pm2"
   version: "2.x.x"

mysql_root_username: root
mysql_root_password: ""
mysql_root_password_update: yes
mysql_databases:
  - name: adonis


todolab_frontend_port: "4455"
todolab_backend_port: "3333"

nginx_sites:
  frontend:
    template: nginx_node.config.j2
    server_name: local.todolab.io
    port: "{{ todolab_frontend_port }}"
  backend:
    template: nginx_node.config.j2
    server_name: local.backend.todolab.io
    port: "{{ todolab_backend_port }}"

