---
- name: Retrieve repository directory stat
  stat:
    path: "{{ repository_path }}"
  register: repository

- name: Checkout frontend repository
  git:
    repo: "git@github.com:Todolab/frontend.git"
    dest: "{{ repository_path }}"
    update: no
  when: not repository.stat.exists

- name: Install npm package
  shell: "source {{ workspace_path }}/.nvm/nvm.sh && yarn install"
  args:
    chdir: "{{ frontend_path }}"
    executable: /bin/bash

