---
- name: todolab
  hosts: todolab
  become: yes
  vars_files:
    - vars/config.yml
  roles:
    - debops.apt
    - tersmitten.locales
    - tersmitten.timezone
    - geerlingguy.git
    - { role: kosssi.gitconfig, become: no }
    - moviedo.nvm
    - ocha.yarn
    - DavidWittman.redis
    - jdauphant.nginx
