---
- name: todolab
  hosts: todolab
  become: yes
  vars_files:
    - vars/config.yml
  roles:
    - debops.apt
    - geerlingguy.git
    - { role: kosssi.gitconfig, become: no }
    - tersmitten.locales
    - tersmitten.timezone
    - DavidWittman.redis
    - fubarhouse.nodejs
    - jdauphant.nginx
    - Stouts.mongodb
    - { role: fubarhouse.yarn, become_user: "{{ ansible_user }}" }
