---
- name: todolab
  hosts: todolab
  become: yes
  roles:
    - tersmitten.locales
    - debops.apt
    - tersmitten.timezone
    - geerlingguy.redis
    - geerlingguy.nodejs
    - jdauphant.nginx
    - geerlingguy.mysql
