---
- name: todolab
  hosts: todolab
  become: yes
  roles:
    - debops.apt
    - geerlingguy.git
    - tersmitten.locales
    - tersmitten.timezone
    - geerlingguy.java
    - DavidWittman.redis
    - fubarhouse.nodejs
    - jdauphant.nginx
    - geerlingguy.mysql
