---
- name: todolab
  hosts: todolab
  become: yes
  roles:
    - tersmitten.locales
    - debops.apt
    - tersmitten.timezone
    - geerlingguy.redis
    - fubarhouse.nodejs
    - ocha.yarn
    - geerlingguy.mysql
